"use client";

import { useEffect, useState } from "react";
import {
  PageHeader,
  Card,
  StatCard,
  Badge,
  Skeleton,
  TableShell,
  Button,
  Spinner,
  Input,
  Select,
  Label,
} from "@/components/ui";

interface Summary {
  byStatus: Array<{ status: string; n: number; total: string }>;
  series: Array<{ day: string; totalMinor: string }>;
  totals: {
    successfulPayments: number;
    sumMinor: string;
    feesMinor: string;
    sumDisplay: string;
    feesDisplay: string;
  };
}

interface SchedRow {
  id: string;
  reportType: string;
  frequency: string;
  retentionDays: number;
  nextRunAt: string;
  active: boolean;
  lastRunAt: string | null;
  lastRowCount: number;
}

interface ReportRow {
  id: string;
  reportType: string;
  format: string;
  status: string;
  payloadRef: string | null;
  rowCount: number;
  createdAt: string;
  completedAt: string | null;
}

export default function ReportsPage() {
  const [data, setData] = useState<Summary | null>(null);
  const [reports, setReports] = useState<ReportRow[]>([]);
  const [exporting, setExporting] = useState<"transactions" | "fees" | null>(
    null,
  );
  const [exportError, setExportError] = useState<string | null>(null);
  const [schedules, setSchedules] = useState<SchedRow[]>([]);
  const [schedForm, setSchedForm] = useState({ reportType: "transactions", frequency: "monthly", retentionDays: "90" });
  const [schedBusy, setSchedBusy] = useState(false);
  const [schedError, setSchedError] = useState<string | null>(null);

  function loadSchedules() {
    fetch("/api/report-schedules")
      .then((r) => r.json())
      .then((d) => setSchedules(d.data ?? []))
      .catch(() => setSchedules([]));
  }
  useEffect(loadSchedules, []);

  async function createSchedule(e: React.FormEvent) {
    e.preventDefault();
    setSchedBusy(true);
    setSchedError(null);
    try {
      const res = await fetch("/api/report-schedules", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(schedForm),
      });
      const d = await res.json();
      if (!res.ok) {
        setSchedError(d.error?.message ?? "Could not create schedule");
        return;
      }
      loadSchedules();
    } catch {
      setSchedError("Network error — try again");
    } finally {
      setSchedBusy(false);
    }
  }

  async function cancelSchedule(id: string) {
    await fetch(`/api/report-schedules/${id}`, { method: "DELETE" });
    loadSchedules();
  }

  useEffect(() => {
    fetch("/api/reports/summary")
      .then((r) => r.json())
      .then((d) => setData(d.data ?? null))
      .catch(() => setData(null));
  }, []);

  function loadReports() {
    fetch("/api/reports")
      .then((r) => r.json())
      .then((d) => setReports((d.data ?? []).map((x: ReportRow) => x)))
      .catch(() => setReports([]));
  }
  useEffect(loadReports, []);

  // Poll while any export is still being generated by the worker.
  useEffect(() => {
    if (!reports.some((r) => r.status === "REQUESTED")) return;
    const t = setInterval(() => {
      fetch("/api/reports")
        .then((r) => r.json())
        .then((d) => setReports(d.data ?? []))
        .catch(() => undefined);
    }, 3000);
    return () => clearInterval(t);
  }, [reports]);

  async function requestExport(type: "transactions" | "fees") {
    setExporting(type);
    setExportError(null);
    try {
      const res = await fetch("/api/reports", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ reportType: type }),
      });
      const d = await res.json();
      if (!res.ok) {
        setExportError(d.error?.message ?? "Export request failed");
        return;
      }
      loadReports();
    } catch {
      setExportError("Network error — try again");
    } finally {
      setExporting(null);
    }
  }

  if (!data) {
    return (
      <div className="space-y-6">
        <Skeleton className="h-10 w-64" />
        <div className="grid gap-4 sm:grid-cols-3">
          {[...Array(3)].map((_, i) => (
            <Skeleton key={i} className="h-28" />
          ))}
        </div>
        <Skeleton className="h-72" />
      </div>
    );
  }

  const max = Math.max(...data.series.map((s) => Number(s.totalMinor)), 1);

  return (
    <div>
      <PageHeader
        title="Reports"
        subtitle="Successful payments over the last 30 days — fully exportable from the ledger."
        actions={
          <div className="flex gap-2">
            <Button
              variant="secondary"
              size="sm"
              onClick={() => requestExport("transactions")}
              disabled={exporting !== null}
            >
              {exporting === "transactions" ? (
                <Spinner className="h-4 w-4 text-white" />
              ) : (
                "Export transactions (CSV)"
              )}
            </Button>
            <Button
              variant="secondary"
              size="sm"
              onClick={() => requestExport("fees")}
              disabled={exporting !== null}
            >
              {exporting === "fees" ? (
                <Spinner className="h-4 w-4 text-white" />
              ) : (
                "Export fees (CSV)"
              )}
            </Button>
          </div>
        }
      />
      {exportError ? (
        <p className="mb-4 text-sm text-danger">{exportError}</p>
      ) : null}

      {reports.length > 0 ? (
        <Card className="mb-6 p-6">
          <h2 className="mb-3 font-semibold">Recent exports</h2>
          <TableShell headers={["Report", "Status", "Rows", "Requested", ""]}>
            {reports.slice(0, 8).map((r) => (
              <tr key={r.id} className="hover:bg-surface/60">
                <td className="px-4 py-2.5 font-mono text-xs">
                  {r.reportType}.{r.format}
                </td>
                <td className="px-4 py-2.5">
                  <Badge
                    tone={
                      r.status === "GENERATED"
                        ? "success"
                        : r.status === "FAILED"
                          ? "danger"
                          : "warning"
                    }
                  >
                    {r.status}
                  </Badge>
                </td>
                <td className="px-4 py-2.5">
                  {r.status === "GENERATED" ? r.rowCount : "—"}
                </td>
                <td className="px-4 py-2.5 text-xs text-muted">
                  {new Date(r.createdAt).toLocaleString()}
                </td>
                <td className="px-4 py-2.5 text-right">
                  {r.status === "GENERATED" ? (
                    <a
                      href={`/api/reports/${r.id}/export`}
                      className="text-sm font-medium text-primary hover:underline"
                    >
                      Download
                    </a>
                  ) : r.status === "FAILED" ? (
                    <span className="text-xs text-muted">Failed</span>
                  ) : (
                    <span className="text-xs text-muted">Generating…</span>
                  )}
                </td>
              </tr>
            ))}
          </TableShell>
        </Card>
      ) : null}

      <Card className="mb-6 p-6">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="font-semibold">Scheduled exports</h2>
            <p className="mt-0.5 text-xs text-muted">
              Recurring CSV exports to object storage (S3 in production) with automatic retention cleanup.
            </p>
          </div>
        </div>
        <form onSubmit={createSchedule} className="mt-4 flex flex-wrap items-end gap-3">
          <div>
            <Label htmlFor="sched-type">Report</Label>
            <Select id="sched-type" value={schedForm.reportType} onChange={(e) => setSchedForm({ ...schedForm, reportType: e.target.value })}>
              <option value="transactions">Transactions</option>
              <option value="fees">Fees</option>
            </Select>
          </div>
          <div>
            <Label htmlFor="sched-freq">Frequency</Label>
            <Select id="sched-freq" value={schedForm.frequency} onChange={(e) => setSchedForm({ ...schedForm, frequency: e.target.value })}>
              <option value="monthly">Monthly (1st)</option>
              <option value="weekly">Weekly (Mon)</option>
            </Select>
          </div>
          <div>
            <Label htmlFor="sched-ret">Retention (days)</Label>
            <Input id="sched-ret" inputMode="numeric" className="w-28" value={schedForm.retentionDays} onChange={(e) => setSchedForm({ ...schedForm, retentionDays: e.target.value })} />
          </div>
          <Button type="submit" disabled={schedBusy}>
            {schedBusy ? <Spinner className="h-4 w-4 text-white" /> : "Create schedule"}
          </Button>
        </form>
        {schedError ? <p className="mt-2 text-sm text-danger">{schedError}</p> : null}
        {schedules.length > 0 ? (
          <div className="mt-4">
            <TableShell headers={["Report", "Frequency", "Retention", "Next run", "Last run", ""]}>
              {schedules.map((sc) => (
                <tr key={sc.id} className="hover:bg-surface/60">
                  <td className="px-4 py-2.5 font-mono text-xs">{sc.reportType}.csv</td>
                  <td className="px-4 py-2.5 text-xs capitalize">{sc.frequency}</td>
                  <td className="px-4 py-2.5 text-xs text-muted">{sc.retentionDays} days</td>
                  <td className="px-4 py-2.5 text-xs">{sc.active ? new Date(sc.nextRunAt).toLocaleString() : "cancelled"}</td>
                  <td className="px-4 py-2.5 text-xs text-muted">
                    {sc.lastRunAt ? `${new Date(sc.lastRunAt).toLocaleString()} (${sc.lastRowCount} rows)` : "never"}
                  </td>
                  <td className="px-4 py-2.5 text-right">
                    {sc.active ? (
                      <button className="text-xs text-danger hover:underline" onClick={() => void cancelSchedule(sc.id)}>
                        Cancel
                      </button>
                    ) : (
                      <Badge tone="neutral">OFF</Badge>
                    )}
                  </td>
                </tr>
              ))}
            </TableShell>
          </div>
        ) : (
          <p className="mt-3 text-xs text-muted">No schedules yet — create one and the worker will export automatically.</p>
        )}
      </Card>

      <div className="grid gap-4 sm:grid-cols-3">
        <StatCard
          label="Successful payments"
          value={String(data.totals.successfulPayments)}
        />
        <StatCard label="Total paid out (30d)" value={data.totals.sumDisplay} />
        <StatCard label="Platform fees" value={data.totals.feesDisplay} />
      </div>

      <div className="mt-6 grid gap-6 lg:grid-cols-2">
        <Card className="p-6">
          <h2 className="mb-4 font-semibold">Outgoing volume — last 30 days</h2>
          <div className="flex h-56 items-end gap-1">
            {data.series.map((s) => (
              <div key={s.day} className="group relative flex-1">
                <div
                  className="rounded-t bg-primary/80 transition group-hover:bg-primary"
                  style={{
                    height: `${Math.max((Number(s.totalMinor) / max) * 100, 2)}%`,
                  }}
                  title={`${s.day}: ${(Number(s.totalMinor) / 100).toLocaleString()} KES`}
                />
              </div>
            ))}
            {data.series.length === 0 ? (
              <p className="self-center text-sm text-muted">
                No successful payments in the last 30 days.
              </p>
            ) : null}
          </div>
          <div className="mt-2 flex justify-between text-[10px] text-muted">
            <span>{data.series[0]?.day ?? "—"}</span>
            <span>{data.series[data.series.length - 1]?.day ?? "—"}</span>
          </div>
        </Card>

        <Card className="p-6">
          <h2 className="mb-4 font-semibold">By status (all time)</h2>
          <TableShell headers={["Status", "Payments", "Value"]}>
            {data.byStatus.map((s) => (
              <tr key={s.status} className="hover:bg-surface/60">
                <td className="px-4 py-2.5">
                  <Badge
                    tone={
                      s.status === "SUCCESS"
                        ? "success"
                        : s.status === "FAILED"
                          ? "danger"
                          : "neutral"
                    }
                  >
                    {s.status}
                  </Badge>
                </td>
                <td className="px-4 py-2.5">{s.n}</td>
                <td className="px-4 py-2.5 font-medium">
                  KES {(Number(s.total) / 100).toLocaleString()}
                </td>
              </tr>
            ))}
          </TableShell>
        </Card>
      </div>
    </div>
  );
}
